// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A content moderation AI agent.
 *
 * - moderateContent - A function that handles the content moderation process.
 * - ModerateContentInput - The input type for the moderateContent function.
 * - ModerateContentOutput - The return type for the moderateContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ModerateContentInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the item, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  description: z.string().describe('The description of the item.'),
  title: z.string().describe('The title of the item.'),
});
export type ModerateContentInput = z.infer<typeof ModerateContentInputSchema>;

const ModerateContentOutputSchema = z.object({
  isAppropriate: z
    .boolean()
    .describe('Whether or not the content is appropriate.'),
  reason: z.string().describe('The reason for the content being inappropriate.'),
});
export type ModerateContentOutput = z.infer<typeof ModerateContentOutputSchema>;

export async function moderateContent(input: ModerateContentInput): Promise<ModerateContentOutput> {
  return moderateContentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'moderateContentPrompt',
  input: {schema: ModerateContentInputSchema},
  output: {schema: ModerateContentOutputSchema},
  prompt: `You are an AI content moderator for a clothing swap app.

You will use this information to determine if the content is appropriate for the app.

Consider these guidelines when making your determination:

*   The photo should be of clothing.
*   The photo should not contain nudity or sexually suggestive content.
*   The photo should not contain hate speech or promote violence.
*   The description and title should be relevant to the item in the photo.
*   The description and title should not contain spam or malicious links.

Title: {{{title}}}
Description: {{{description}}}
Photo: {{media url=photoDataUri}}

Based on the above criteria, is the content appropriate? Return a boolean value for isAppropriate.
If isAppropriate is false, provide a detailed explanation in the reason field.`,
});

const moderateContentFlow = ai.defineFlow(
  {
    name: 'moderateContentFlow',
    inputSchema: ModerateContentInputSchema,
    outputSchema: ModerateContentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
